### ISSUE TITLE
Apply apply depth offset

### ISSUE THREAD

**Issue by dangvanthanh** [ErikGartner/dTree#101]
HI @ErikGartner 

In your code below. Why use code in here? In my opinion, the code isn't necessary.

https://github.com/ErikGartner/dTree/blob/a0736a8dcace99cc4b85b7c7cc48449b81185927/src/dtree.js#L82-L95

**Comment by ErikGartner** [comment]
It's used to move a sub-tree down by `depthOffset` number of levels. I use it several of my trees.
