### ISSUE TITLE
Broken SVG in Vue

### ISSUE THREAD

**Issue by overboy20** [ErikGartner/dTree#104]
Hello, I am trying to use dTree in my Vue project and got the following result:

![screenshot-127 0 0 1_8000-2020 05 03-21_26_52](https://user-images.githubusercontent.com/13350284/80922361-466df700-8d85-11ea-8734-aac1a70f64c5.png)

In Console no errors.

Are there any ideas how to fix this?

**Comment by overboy20** [comment]
Found a reason - styles were not applied because it modified DOM by itself and Vue don't know anything about these elements.

**Comment by free-might-bobger** [comment]
@overboy20 - how did you fix this one?
