### ISSUE TITLE
First Cousin Marriage issue

### ISSUE THREAD

**Issue by colorado76** [ErikGartner/dTree#107]
Marriage to a first cousin ,creates 2 identical branches. Is there a way to solve it ? . Please see attached image.  Here E and F are repeated twice. 

Thanks in advance.
![familytree](https://user-images.githubusercontent.com/63335488/84057378-35905100-a9d5-11ea-978f-8c3ee804f242.png)

**Comment by ErikGartner** [comment]
Hi,

This is a known limitation unfortunately.

Feel free to submit a pull request if you make a solution.

Best regards,
Erik

**Comment by colorado76** [comment]
Thanks for

**Comment by colorado76** [comment]
Thanks for the reply and the works. 
I am going to see if I can add hidden nodes.
