### ISSUE TITLE
Appreciation

### ISSUE THREAD

**Issue by zuhairabs** [ErikGartner/dTree#127]
# Shajra - Web App
```python
// I have developed a website using your library
// Thanks for this library.
```

<b>Link: </b> https://shajra-app.vercel.app

![Desktop - 1](https://user-images.githubusercontent.com/41848715/142657902-8e6b7b29-83b2-4ea8-9f91-f90289c12edd.png)

**Comment by ErikGartner** [comment]
Glad to hear you like it!
