### ISSUE TITLE
Can we add image ?

### ISSUE THREAD

**Issue by siddhesh-vartak98** [ErikGartner/dTree#141]
I am currently making a family tree. I need to add a photo of each individual. Can I add images to the tree?
Image be any shape either circle or square.

**Comment by ErikGartner** [comment]
Yes you can. You need to add a custom noderenderer (defining how to render each node) and then add a link to the image in the extra attribute of the node.

**Comment by ErikGartner** [comment]
Something like this https://jsfiddle.net/q8zn5ms4/4/ (the size of the image is really bad but you get the main idea).
