### ISSUE TITLE
Can we Add Image of person in the Node? 

### ISSUE THREAD

**Issue by siddhesh-vartak98** [ErikGartner/dTree#142]
First thank you for your support. I am making a family tree, so I need to add person images on the node. How can in add image on the node?   The attachment of photo as show reference. Can we make as same show in photo?
![nodeWithImage](https://user-images.githubusercontent.com/56190795/216060083-1339fd46-0663-42d1-9d5e-fa4cb62d4d95.jpg)

**Comment by ErikGartner** [comment]
Hi, as I replied in #141, you can add images, see the attached example. If you want something exactly like that you need to style the noderenderer and CSS file accordingly. It's beyond my capacity to help you with that though.
Good luck!

**Comment by siddhesh-vartak98** [comment]
Thank you
