### ISSUE TITLE
Onclicking the node change its class

### ISSUE THREAD

**Issue by mpsbhat** [ErikGartner/dTree#147]
Namaste,
Is there any simple way to change the class of the node on clicking on it, maybe for highlighting the clicked node.

Thanks in advance!

**Comment by ErikGartner** [comment]
Hi,

You can make your own callback for when the user clicks the node (using `nodeClick`). In the javascript you can for example add / change the class of the node to enable highlighting.

Best

**Comment by mpsbhat** [comment]
Understood.
I should use something like `document.getElementById(nodeid).className = "classname";` inside `nodeClick` callback.

Thank you for the suggestion @ErikGartner!
