### ISSUE TITLE
How do I insert images into the tree?

### ISSUE THREAD

**Issue by lilsizzo** [ErikGartner/dTree#33]
Would the tree be able to support images? img tag or background image? The one i've tried inserting display image but now in the nodes and it doesnt zoom in and out.

**Comment by ErikGartner** [comment]
You should be able to insert images into nodes without any problem assuming you're using the library on your own webpage and you use a custom node renderer.

Show me some code snippets, like your custom renderer and your options object.

If you're using [Treehouse ](treehouse.gartner.io) then I don't think it is possible using just [Swag helpers](http://elving.github.io/swag/). Treehouse is mainly intended for demoing and not all the advanced features aren't available.

**Comment by lilsizzo** [comment]
Hi ErikGartner, 
I think I have managed to get that fixed. Perhaps put it at the wrong place. 

Thanks a lot
