### ISSUE TITLE
Upgrade to d3 v4.

### ISSUE THREAD

**Issue by ErikGartner** [ErikGartner/dTree#36]
Currently dTree supports only d3 v3 but upgrading may add some nice benefits.

**Comment by Vacilando** [comment]
Does not work with https://d3js.org/d3.v4.min.js yet -- any progress on that?

**Comment by ErikGartner** [comment]
No sorry, I haven't had the time. Feel free to make a pull request fixing the issue.

**Comment by 0x4F72** [comment]
started working on it recently. so you might see a pr in near future

**Comment by ErikGartner** [comment]
That's great! :)
