### ISSUE TITLE
Question: generate json

### ISSUE THREAD

**Issue by lilsizzo** [ErikGartner/dTree#39]
How do I generate the json out in php? Ive been trying for weeks but to no avail.

**Comment by ErikGartner** [comment]
What's the question? What json are you referring to?

Are you asking how you can create the data object from PHP and pass it to `dTree.init()`?
I haven't used PHP in quite a while, but a cursory search yielded this: http://stackoverflow.com/questions/6351949/passing-php-objects-to-javascript

/Erik

**Comment by lilsizzo** [comment]
Ah yeah, to generate  the json out in the proper format. Was struggling and finally go the breakthrough. Thanks a bunch!
