### ISSUE TITLE
Add position data to click callback

### ISSUE THREAD

**Issue by webloong** [ErikGartner/dTree#42]

**Comment by ErikGartner** [comment]
Controlling the graph for centering etc is proposed in #20 and not yet supported.
I'm going to make this ticket about adding position data to the click callback.

**Comment by webloong** [comment]
Look forward to your update every time

**Comment by MrMartiniMo** [comment]
Hello, I have created a pull request for this. The callback functions of the click events are called here with the "this" context. So it is possible to query the mouse coords with `d3.mouse(this)` within the callback function.

```javascript
dTree.init(jsonData, {
	target: "#target",
	callbacks: {
		nodeClick: function (name, extra, id) {
			console.log(d3.mouse(this))
		},
		nodeRightClick: function (name, extra, id) {
			console.log(d3.mouse(this))
		},
	}
})
```

@ErikGartner Sorry for the mess with the pull requests. I don't have a lot of experience in that area.

**Comment by ErikGartner** [comment]
Hi @MrMartiniMo, good job! I applied your changes to all callbacks. This issue is now solved as you note above.
