### ISSUE TITLE
Visual artifacts while panning the tree

### ISSUE THREAD

**Issue by kevinfszu** [ErikGartner/dTree#44]
There will be some horizontal lines occur if you drag the tree

**Comment by ErikGartner** [comment]
Hey!

Thanks for reporting the bug, however please give some more information about the bug.

- What browser do you use? What version?
- What operating system do you use? What version?
- Attach a screenshot of the error if possible.
- How do you recreate the problem? Does it always occur or do you do something special before?

/Erik

**Comment by kevinfszu** [comment]
- Chrome 55.0.2883.87 m (64-bit)
- Windows 10
- ![qq 20170108130011](https://cloud.githubusercontent.com/assets/5536550/21747462/6c6eab82-d5a2-11e6-9724-734e180c2f03.png)
- Try zoom and drag the tree,it does't occur everytime,but if you try for more times,you will find it.

**Comment by ErikGartner** [comment]
Thanks for reporting the problem, I can verify that this happens now on my computer too.

**Comment by ErikGartner** [comment]
@kevinfszu The new version of dTree uses d3 v4. Perhaps this fixes the issue?

**Comment by ErikGartner** [comment]
As of late I've not noticed this problem since upgrade to v4 and using newer Chrome versions. Marking this as solved unless somebody still have this issue.
