### ISSUE TITLE
How do I add custom node styles?

### ISSUE THREAD

**Issue by ucay** [ErikGartner/dTree#46]
I need to know who already passed away. So I add `rip: true` in node of my JSON format.
Then add a class `rip` to node via custom `_nodeRenderer` function.
```
.rip p{
    color: #757474;
    background: url('../img/rip.svg') no-repeat;
    background-size: 9px;
    padding-left: 9px;
}
```
![screenshot from 2017-01-19 12 42 27](https://cloud.githubusercontent.com/assets/3348846/22095123/dcf0113e-de44-11e6-9081-dfe3eb70fc5d.png)

Yeah, at least it works for me, but still looks ugly :laughing:  (my bad in styling)
Is this the right way?
Or could it be the next feature?

**Comment by ErikGartner** [comment]
Hi @ucay!

That is definitely one solution. Though you should be able to use just the class attribute.
For example:
```json
{
  "name": "Marcus",
  "class": "man dead"
}
```
That will give the node both CSS styles. Sometimes depending on the type of attributes in the CSS-style it might not work correctly and you might have to have to different CSS-styles like: `man` and `man-dead`.

Does this answer your question?

/Erik

**Comment by ucay** [comment]
that's right, thanks...
