### ISSUE TITLE
NodeClick is having the name parameter undefined

### ISSUE THREAD

**Issue by ishan28mkip** [ErikGartner/dTree#50]
nodeClick callback is getting the name parameter undefined, probably happened because of d3 version change, just need to change d.name to d.data.name when calling the callback. Will send a pr when free, also leaving a comment on the code if someone else is working on it.

**Comment by ErikGartner** [comment]
Thanks, you're absolutely right!
I'll merge your pr as fast as possible. :-)

**Comment by ErikGartner** [comment]
Thanks for the bug report @ishan28mkip. I had some spare time so I released a fix.
Let me know if you have any remaining problems :)
