### ISSUE TITLE
Incorrect marriage lines for multiple marriages

### ISSUE THREAD

**Issue by lipedeitos** [ErikGartner/dTree#53]
Hi! First of all, i really like the plugin! Actually it attends me in everything, one thing i've noticed is that when you add 3 spouses to the same person (1 actual spouse and 2 divorced) the middle one kind bug...

Here's the fiddle..
https://jsfiddle.net/tpde0cer/214/

When you add 2 spouses it works really well
https://jsfiddle.net/tpde0cer/215/

Thanks for the attention and sorry about my english hehe!
Cheers!

**Comment by ucay** [comment]
It's happen when the 2nd or 3rd marriage has more than one child...

**Comment by ErikGartner** [comment]
Hey @lipedeitos!

Glad to hear you like the library. :-)

Verified the bug, I'm currently doing a lot of interviewing for but I'll try to fix this bug as soon as I can. 

@ucay I tried to add a second child to the third marriage and that doesn't break "that line". Was this what you meant? https://jsfiddle.net/tpde0cer/218/

**Comment by ErikGartner** [comment]
Should have released a fix now. Please verify that it works.

This jsfiddle uses the new patched versions (2.0.2):
https://jsfiddle.net/tpde0cer/220/
