### ISSUE TITLE
Features: Disable scrolling e double right click zoom out

### ISSUE THREAD

**Issue by lipedeitos** [ErikGartner/dTree#54]
Hi Erik!

There are any chances of one of this features be add to the plugin?

**Disable scrolling:**  Actually I am setting the width of the svg to 100% and it is working fine, but when the user starts to scroll the screen, the cursor come over the dTree layer and it starts to zoom in and zoom out, sometimes it would be nice to disable scrolling zoom in and zoom out, so the user keep scrolling the screen.

**Double right click:** if we disable the scroll (zoom in/out) we gonna need to add something like double right click to work as zoom out (double left already works as zoom in).

Well thats it, i don't know how much time you would spend on this features, but i guess they will help making it more customizable.

Cheers.

**Comment by ErikGartner** [comment]
Hi @lipedeitos!

Thanks for your feedback!

To zoom out using double clicking you can already use  *shift + double left click*.

Regarding disabling scrolling this has already been requested in #49. So I'm gonna close this issue. Please continue the discussion about this feature in the original issue. 

I can say however that I'm gonna be very busy these coming weeks. Feel free to make a pull request and if you need help I'll try to guide you. You can also make a manual fix disabling the d3 scroll on zoom. See this: https://github.com/d3/d3-zoom/issues/80

/Erik

**Comment by lipedeitos** [comment]
For those who need to add a emergency fix:

`d3.select(selector)
                .on("wheel.zoom", null)
                .on("mousewheel.zoom", null)
                .on("mousemove.zoom", null)
                .on("DOMMouseScroll.zoom", null)`

Cheers!
