### ISSUE TITLE
Composite family

### ISSUE THREAD

**Issue by lhf1990729** [ErikGartner/dTree#56]
treeData = [{
  "name": "Niclas Superlongsurname",
  "class": "man",
  "textClass": "emphasis",
  "marriages": [{
    "spouse": {
      "name": "Iliana",
      "class": "woman"
    },
    "children": [{
      "name": "James",
      "class": "man",
       "children": [{
          "name": "james 1",
          "class": "man",
          
          }],
      "marriages": [{
        "spouse": {
          "name": "Alexandra",
          "class": "woman",
           "children": [{
          "name": "james 1",
          "class": "man",
          
          }]
        },
        "children": [{
          "name": "Eric",
          "class": "man",
          "marriages": [{
            "spouse": {
              "name": "Eva",
              "class": "woman"
            }
          }]
        }, {
          "name": "Jane",
          "class": "woman"
        }, {
          "name": "Jasper",
          "class": "man"
        }, {
          "name": "Emma",
          "class": "woman"
        }, {
          "name": "Julia",
          "class": "woman"
        }, {
          "name": "Jessica",
          "class": "woman"
        }]
      }]
    }]
  }]
}]

dTree.init(treeData, {
  target: "#graph",
  debug: true,
  height: 800,
  width: 1200,
  callbacks: {
    nodeClick: function(name, extra) {
      console.log(name);
    }
  }
});

**Comment by ErikGartner** [comment]
Please specify what the issue. Preferable with a link to a jfiddle demo.

**Comment by lhf1990729** [comment]
just like this issues!   https://github.com/ErikGartner/dTree/issues/51

**Comment by ErikGartner** [comment]
Oh, I see. I'll close this duplicate then. Please use 51 for discussion.
