### ISSUE TITLE
How complicated can your tree handle?

### ISSUE THREAD

**Issue by timlyg** [ErikGartner/dTree#58]
Can it handle [Habsburg family tree?](https://learnearnandreturn.files.wordpress.com/2011/07/777px-carlos_segundo801.png)

Also, I would like to contribute with nodes with photos, if it has not been done yet.

Thanks.

**Comment by ErikGartner** [comment]
No, I'm sorry it doesn't support that type of "recursive relationships".

**Comment by ErikGartner** [comment]
Regarding photos it is fully supported since you can use custom renderers for the nodes that displays custom html (including an img tag).

**Comment by timlyg** [comment]
Oh...LOL, not many families out there that complex. Thanks for the reply and answer!
