### ISSUE TITLE
Problem displaying very large trees

### ISSUE THREAD

**Issue by Spiruel** [ErikGartner/dTree#63]
I have a moderately large tree successfully working at https://jsfiddle.net/039520ra/

However when I try to increase the tree further, I get the error 'e.sort is not a function' https://jsfiddle.net/q0Ldsxb9/

Is there a maximum tree size that dTree can support?

**Comment by ErikGartner** [comment]
This is not a bug with displaying large trees. You're data is simply incorrect.

Your node for `Joanna Lees` is not in a an array as it should be.

/Erik
