### ISSUE TITLE
Uncaught ReferenceError: dTree is not defined

### ISSUE THREAD

**Issue by vishnuraj007** [ErikGartner/dTree#70]
What i did is:
-Downloaded the project from github
-npm install --save-dev
-npm run-script build
-npm run-script demo

Error that i am getting in chrome is:
Uncaught ReferenceError: dTree is not defined
    at (index):46
    at Object.<anonymous> (d3.v4.min.js:2)
    at k.call (d3.v4.min.js:2)
    at XMLHttpRequest.e (d3.v4.min.js:2)

Could you help me out here .?

**Comment by ErikGartner** [comment]
What browser, version etc are you using?

Hard to tell why this isn't working

**Comment by vishnuraj007** [comment]
I tried in Google chrome  64.0.3282.167 
and Microsoft Edge 41.16299.15.0

**Comment by ErikGartner** [comment]
I could not replicate the error using Chrome 64.0.3282.167.
What I did was:

```bash
npm install -g gulp
npm install
npm run-script demo
```

Perhaps checking out the repository and start over using the commands above.
