### ISSUE TITLE
DTree is not showing up properly in Android Kitkat Webview

### ISSUE THREAD

**Issue by gkarmakar123** [ErikGartner/dTree#72]
We created the tree on server side, in Cake PHP 3.5
The final rendered SVG is showing up properly in desktop browsers and iOS webviews and browsers but the same image is not rendered properly in Android Kitkat webview.

Any help on this is appreciated.

**Comment by ErikGartner** [comment]
I'm sorry I don't own an Android phone. Perhaps look at the console / debug from the android emulator?

**Comment by ucay** [comment]
Is this related with dTree ?
Aren't there missing configuration when rendering SVG in your Android webview?
If you build it with Ionic (for example), try post your problem in their forum.

**Comment by ErikGartner** [comment]
I had problem with fullscreen rendering of the Treehouse for iOS too, but fixed this in the latest version.

The problem lay in determining the proper SVG size. See the commit on how to do this.
https://github.com/ErikGartner/treehouse/commit/96e52886936fc320aa9950dcc79fdbec2194dc0b#diff-8f15dfdaaa2ab4eddc27b3a63e75774aL43

See also if the fullscreen SVG works on Android here:

https://treehouse.gartner.io/g/f/58e58be650453b6d49d7
