### ISSUE TITLE
How to use with React Js?

### ISSUE THREAD

**Issue by mk48** [ErikGartner/dTree#75]
Thanks for the excellent library.

I just tried to use with React Js and couldn't get through.
Below is my approach. Could any please help me on this?

```
import React from 'react';
import dTree from 'd3-dtree';
import _ from 'lodash';
import * as d3 from "d3";

class FamTree extends React.Component { 
  componentDidMount() {
    let treeData = [{
      name: "Father",
      depthOffset: 1,
      marriages: [{
        spouse: {
          name: "Mother",
        },
        children: [{
          name: "Child",
        }]
      }],
      extra: {}
    }];

    dTree.init(treeData, {target: "#graph", height:800, width: 1200, debug:true});
  }

  render() {
    return (
      <div>
        <div id="graph"></div>
      </div>
    );
  }
}

export default FamTree;
```
I am getting "d3 is not defined"

![image](https://user-images.githubusercontent.com/3082469/39183440-9c30eea8-47dd-11e8-9e3d-e17ace6c9465.png)

**Comment by ErikGartner** [comment]
I'm not that familiar with react. Basically you just need to make that D3 is loaded before loading dTree.

**Comment by mk48** [comment]
I will try to find a way, If I get any then I will post my answer here.

**Comment by theoperatore** [comment]
@mk48 I believe the library depends on `d3` being available globally. so something like

```js
// in your src/index.js
import d3 from 'd3';
...
window.d3 = d3;
```

should do the trick.

**Comment by mk48** [comment]
thanks @theoperatore , below code solved the issue

```javascript
// in your src/index.js
import * as d3 from 'd3';
...
window.d3 = d3;
```

**Comment by atefBB** [comment]
> @mk48 I believe the library depends on `d3` being available globally. so something like
> 
> ```js
> // in your src/index.js
> import d3 from 'd3';
> ...
> window.d3 = d3;
> ```
> 
> should do the trick.

I think this is not recommanded in `react` (to assign a new variable to `window`) !
