### ISSUE TITLE
Radial tree

### ISSUE THREAD

**Issue by serber** [ErikGartner/dTree#79]
Is there any way to make radial tree like this?
![image](https://user-images.githubusercontent.com/791007/41868127-d392b30c-78bd-11e8-849e-f6434fe4b314.png)

**Comment by ErikGartner** [comment]
Should be possible but it would require changing the layout from D3 which would require adding it as new feature to dTree.

**Comment by ErikGartner** [comment]
I'll close this issue as I don't think radial trees is inline with dTree's goals of being a genealogy tree.
