### ISSUE TITLE
Safari rendering issue. 

### ISSUE THREAD

**Issue by saqibomer** [ErikGartner/dTree#81]
I am using dTree to create a family tree. I am using custom node to create nodes. It is working fine on Chrome but not working on Safari. Nodes are not rendered properly. 
<img width="664" alt="screenshot 2018-10-29 at 5 10 44 pm" src="https://user-images.githubusercontent.com/7654562/47648988-9884f980-db9d-11e8-9c2f-84240a664ed2.png">

[JSFiddle](https://jsfiddle.net/saqibomer/emsv8pyn/4/) link.

**Comment by saqibomer** [comment]
Added jsfiddle link

**Comment by ErikGartner** [comment]
Hi!

I have had a look at your code and it's hard for me to figure exactly what's wrong. My best suggestion is using the library directly (without hacking the dTree source code) with the callbacks. Then successively adding more adding more complex nodes through the callback `nodeRenderer`. 

I've modified the example on jsfiddle to use the callback and this works fine in both chrome and safari.

https://jsfiddle.net/tpde0cer/992/

Good luck with the bug hunt!
/Erik
