### ISSUE TITLE
Image Support

### ISSUE THREAD

**Issue by jpdaut** [ErikGartner/dTree#82]
Instead of text, can nodes be images?  Or, can nodes embed image and text?

**Comment by ErikGartner** [comment]
Yes for sure! You just write callback for the rendering of the nodes (using the `nodeRenderer` callback) then your nodes can be anything written in html, like a div containing an image and text.

**Comment by jpdaut** [comment]
Great. Can you direct me to a model on how to make the callback?  That would be very appreciated, thank you.

**Comment by ErikGartner** [comment]
Yes, I've updated the official |JSFiddle](https://jsfiddle.net/tpde0cer/998/) to use the nodeRenderer callback. It just sets it to the default value but you can change it to include <img> tags for images etc. Basically you can use any valid HTML for foreign objects in SVG.

**Comment by jpdaut** [comment]
Fantastic.  This works great!  Thank you
