### ISSUE TITLE
Make all node the same maximal height

### ISSUE THREAD

**Issue by jpdaut** [ErikGartner/dTree#83]
Names in my tree wrap into 2 lines or 3 lines depending on their length.  This makes the nodes different heights.  It would look better if all nodes were the same height.  Is there a way to force all nodes to have the same height = height of the highest node?

**Comment by ErikGartner** [comment]
Yes, by using the custom node renderer call back you can use any HTML / CSS to style and format your nodes. https://jsfiddle.net/tpde0cer/998/

/Erik

**Comment by jpdaut** [comment]
So in nodeRenderer I changed from :
node += 'style="height:100%;width:100%;" ';

to a fixed pixel height, 125px :
node += 'style="height:125px;width:100%;" ';

This works because the lower div overflows visible outside the SVG area :

<foreignObject x="79.99999999999875px" y="923.5px" width="100px" height="53px" id="89"><div style="height:125px;width:100%;" class="woman" id="node84">
<p align="center" class="nodeText"><img class="avatar" src="mugshots/AnneC.JPG">Anne Mauvenist</p></div></foreignObject>

I originally thought the <foreignobject> SVG element itself should be scaled (to a fixed height)

But you're saying have the lower DIV over the SVG area like this, and it's ok?
