### ISSUE TITLE
How to get the id of the data when clicked

### ISSUE THREAD

**Issue by FingersKey** [ErikGartner/dTree#85]
```
nodeClick: function(name, extra, id) {
   console.log(name);
   console.log(id);
}
```

This id is the serial number is not in my data.

**Comment by FingersKey** [comment]
When rendering a node, if I can return the metadata in terms of scalability, I think it is a big boost.

**Comment by ErikGartner** [comment]
If you've added your own id in your data. Store it under the "extra" field to have access to it through the extra argument.

/Erik
