### ISSUE TITLE
How to reload the graph with new data?

### ISSUE THREAD

**Issue by rajkumar0143** [ErikGartner/dTree#86]

**Comment by ErikGartner** [comment]
Call `_update(data)` on the graph object.

https://github.com/ErikGartner/dTree/blob/976caaa647999a42e8811da6c2c1d0946a2b6b4c/src/builder.js#L61

**Comment by rajkumar0143** [comment]
Thanks to replay....
I tried a lot but it's 'graph' not update when i am refresh,  How to call _update(data) in your given example
