### ISSUE TITLE
How do I use dTree with npm?

### ISSUE THREAD

**Issue by migmacdev** [ErikGartner/dTree#88]
I'm getting the error "ReferenceError: d3 is not defined", the npm D3 module is installed, any help to fix this issue?

**Comment by ErikGartner** [comment]
How are you using dTree?
 
I'm not too familiar with webpack etc. If you just load the dTree.js in a <script> tag make sure you load d3 before.

**Comment by kensplanet** [comment]
The way I solved this was to,

```
import * as d3 from d3;

// later in your constructor
window.d3 = d3;
```
